encoding: utf-8

# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            bazforge
tagline:          'UTC+2 based dog owner & gamer'
description:      'idkfa iddqd'
url:              http://bazforge.com

author:
  name:           'Mike Adolphs'
  url:            https://twitter.com/fooforge

paginate:         10

# Custom vars
version:          0.2.1

github:
  repo:           https://github.com/fooforge/bazforge.com

gems:
  - jekyll-sitemap
  - emoji_for_jekyll

flickr:
  api_key: dummy_key

image:
  source: "public/img/_original"
  output: "public/img"
  presets:
    thumbnail:
      attr:
        class: "thumbnail-img"
        itemprop: "image"
      width: "200"
    thumbnail-large:
      attr:
        class: "thumbnail-large-img"
        itemprop: "image"
      width: "350"

picture:
  source: "public/img/_original"
  output: "public/img"
  markup: "picturefill"
  presets:
    default:
      ppi: [1]
      attr:
        class: "default-img"
        itemprop: "image"
      source_large:
        media: "(min-width: 50em)"
        width: "800"
      source_medium:
        media: "(min-width: 25em)"
        width: "400"
      source_small:
        media: "(min-width: 12.5em)"
        width: "200"
      source_default:
        width: "1000"
